export const TRASPASO_BODEGA = "TRASPASO BODEGA"

export const TIPOS_MOV_ENT = [
  "COMPRA",
  "COSECHA A STOCK",
  "DEVOLUCION CC",
  "TOMA INVENTARIO ENT",
  "MUESTRA GRATIS",
]

export const TIPOS_MOV_SAL = [
  "VENTA",
  "CONSUMO CC",
  "TRASPASO BODEGA",
  "MERMA",
  "DEVOLUCION PROVEEDOR",
  "TOMA INVENTARIO SAL",
]

export const PREFIJO_MOV: Record<string, string> = {
  COMPRA: "COMP",
  "COSECHA A STOCK": "COS",
  "DEVOLUCION CC": "DCC",
  "TOMA INVENTARIO ENT": "TIE",
  "MUESTRA GRATIS": "MUE",
  VENTA: "VTA",
  "CONSUMO CC": "CCC",
  "TRASPASO BODEGA": "TRB",
  MERMA: "MER",
  "DEVOLUCION PROVEEDOR": "DEV",
  "TOMA INVENTARIO SAL": "TIS",
}