// Catálogo de roles y permisos (ADR-004). Copiado literal del monolito de
// referencia (index.html: PERMISSIONS, ROLE_PERMS, ROLE_LABELS). 6 roles, 38
// permisos granulares. Hoja: no importa otras capas.

// [clave, etiqueta legible]
export const PERMISOS = [
  ["productos.ver", "Ver productos"],
  ["productos.crear", "Crear/editar productos"],
  ["productos.eliminar", "Eliminar productos"],
  ["bodegas.ver", "Ver bodegas"],
  ["bodegas.crear", "Crear/editar bodegas"],
  ["proveedores.ver", "Ver proveedores"],
  ["proveedores.crear", "Crear/editar proveedores"],
  ["clientes.ver", "Ver clientes"],
  ["clientes.crear", "Crear/editar clientes"],
  ["centrosCosto.ver", "Ver centros de costo"],
  ["centrosCosto.crear", "Crear/editar centros de costo"],
  ["tomas.ver", "Ver tomas de inventario"],
  ["tomas.crear", "Iniciar y capturar tomas de inventario"],
  ["tomas.autorizar", "Autorizar y aplicar ajustes de inventario"],
  ["movimientos.ver", "Ver movimientos"],
  ["movimientos.crear", "Crear movimientos"],
  ["movimientos.editar", "Editar movimientos"],
  ["movimientos.anular", "Anular movimientos"],
  ["stock.ver", "Ver stock"],
  ["usuarios.ver", "Ver usuarios"],
  ["usuarios.crear", "Crear/editar usuarios"],
  ["config.ver", "Ver configuración"],
  ["config.editar", "Editar configuración"],
  ["cuaderno.ver", "Ver Cuaderno de Campo"],
  ["cuaderno.editar", "Editar Cuaderno de Campo (registros, órdenes, paños)"],
  ["cuaderno.confirmar", "Confirmar aplicaciones de órdenes"],
  ["cuaderno.panos", "Gestionar paños (crear, editar, eliminar)"],
  ["presupuesto.ver", "Ver Control de Presupuesto (Huerto Cerezos)"],
  [
    "presupuesto.editar",
    "Actualizar datos del Control de Presupuesto (subir Excel)",
  ],
  ["mantenciones.ver", "Ver módulo de Servicio y Mantención"],
  ["mantenciones.crear", "Crear y editar órdenes de trabajo"],
  ["mantenciones.facturar", "Registrar facturas de servicio y mantención"],
  ["mantenciones.eliminar", "Eliminar órdenes de trabajo y facturas"],
  ["conteos.ver", "Acceder al módulo de Conteos en terreno"],
  ["conteos.revisar", "Revisar conteos: exportar Excel y aplicar a estimación"],
  ["invplantas.ver", "Acceder al Inventario de Huerto (conteo de plantas)"],
  ["invplantas.revisar", "Revisar inventario de plantas: exportar y ver mapa"],
  ["invplantas.editar", "Editar estado de árboles en el mapa de plantas"],
] as const

export const ROLES = [
  "admin",
  "gerente",
  "agronomo",
  "operador",
  "consulta",
  "opconteos",
] as const

export const ROLE_LABELS: Readonly<Record<string, string>> = {
  admin: "Administrador",
  gerente: "Gerente",
  agronomo: "Admin. Agrónomo",
  operador: "Operador",
  consulta: "Consulta",
  opconteos: "OP. CONTEOS",
}

// Permisos típicos por rol (defaults de auto-marcado). admin = todos.
export const ROLE_PERMS: Readonly<
  Record<(typeof ROLES)[number], readonly string[]>
> = {
  admin: PERMISOS.map((p) => p[0]),
  gerente: [
    "productos.ver",
    "bodegas.ver",
    "proveedores.ver",
    "clientes.ver",
    "centrosCosto.ver",
    "tomas.ver",
    "movimientos.ver",
    "stock.ver",
    "usuarios.ver",
    "config.ver",
    "cuaderno.ver",
    "mantenciones.ver",
    "presupuesto.ver",
  ],
  agronomo: [
    "productos.ver",
    "bodegas.ver",
    "stock.ver",
    "movimientos.ver",
    "config.ver",
    "cuaderno.ver",
    "cuaderno.editar",
    "cuaderno.confirmar",
    "cuaderno.panos",
    "conteos.ver",
    "conteos.revisar",
    "invplantas.ver",
    "invplantas.revisar",
    "presupuesto.ver",
  ],
  operador: [
    "productos.ver",
    "productos.crear",
    "bodegas.ver",
    "proveedores.ver",
    "proveedores.crear",
    "clientes.ver",
    "clientes.crear",
    "centrosCosto.ver",
    "centrosCosto.crear",
    "movimientos.ver",
    "movimientos.crear",
    "stock.ver",
    "tomas.ver",
    "tomas.crear",
    "config.ver",
  ],
  consulta: [
    "productos.ver",
    "bodegas.ver",
    "proveedores.ver",
    "clientes.ver",
    "centrosCosto.ver",
    "movimientos.ver",
    "stock.ver",
    "tomas.ver",
    "config.ver",
  ],
  opconteos: ["conteos.ver", "invplantas.ver"],
}
